return {
  comp = require('lure.comp'),
  iolist = require('lure.iolist'),
  log = require('lure.log'),
  match = require('lure.match'),
  scheme_flatten_blocks = require('lure.scheme_flatten_blocks'),
  scheme = require('lure.scheme'),
  scheme_luapp = require('lure.scheme_luapp'),
  scheme_macro_anf = require('lure.scheme_macro_anf'),
  scheme_macros = require('lure.scheme_macros'),
  scheme_match = require('lure.scheme_match'),
  scheme_pretty = require('lure.scheme_pretty'),
  se = require('lure.se'),
  se_match = require('lure.se_match'),
  set = require('lure.set'),
  slc = require('lure.slc'),
  slc_runtime = require('lure.slc_runtime'),
  smc = require('lure.smc'),
  string_dsl = require('lure.string_dsl'),
}
